import SwiftUI

private struct StoryPage {
    let vocab: VocabItem
    let text: String
}

struct StoryMissionView: View {
    let vocab: VocabItem
    let onComplete: (String) -> Void

    @Environment(\.dismiss) private var dismiss
    @State private var phase: StoryPhase = .reading(page: 0)
    @State private var quizSelected: String? = nil
    @State private var quizRevealed = false
    @State private var quizChoicesCache: [VocabItem]? = nil
    /// Story lines generated by Gemma — nil until generation finishes.
    @State private var storyTexts: [String]? = nil
    /// Set if Gemma generation fails; the templated story is used instead.
    @State private var storyError = false
    @Environment(\.verticalSizeClass) private var verticalSizeClass
    private var isLandscape: Bool { verticalSizeClass == .compact }

    enum StoryPhase: Equatable {
        case reading(page: Int)
        case quiz
    }

    /// The three vocab items this story teaches: the target plus two from the
    /// same category. Deterministic, so it is stable across view updates.
    private var storyItems: [VocabItem] {
        let related = VOCAB.filter { $0.cat == vocab.cat && $0.id != vocab.id }
        var items = [vocab] + Array(related.prefix(2))
        if items.count < 3 {
            items += VOCAB.filter { !items.map(\.id).contains($0.id) }.prefix(3 - items.count)
        }
        return Array(items.prefix(3))
    }

    /// The story pages — Gemma-written text once ready, a template otherwise.
    private var pages: [StoryPage] {
        let items = storyItems
        return items.indices.map { i in
            let text = (storyTexts.map { i < $0.count ? $0[i] : nil } ?? nil)
                ?? Self.fallbackText(i, items[i])
            return StoryPage(vocab: items[i], text: text)
        }
    }

    /// Template story line, used until Gemma's story arrives or if it fails.
    private static func fallbackText(_ index: Int, _ item: VocabItem) -> String {
        let word = item.en.lowercased()
        switch index {
        case 0:
            return "Q found \(article(word)) \(word)! In Mandarin, it's '\(item.hanzi)' — say \(item.pinyin)."
        case 1:
            return "Look — \(article(word)) \(word)! '\(item.hanzi)' (\(item.pinyin)). Can you say it?"
        default:
            return "Amazing work! You're becoming a Mandarin agent. Remember '\(item.hanzi)' (\(item.pinyin)) — \(word)."
        }
    }

    /// "a" / "an" for the given word.
    private static func article(_ word: String) -> String {
        "aeiou".contains(word.lowercased().first ?? " ") ? "an" : "a"
    }

    private func loadStory() async {
        do {
            let texts = try await QuackGemma.shared.generateStory(items: storyItems)
            await MainActor.run { withAnimation { storyTexts = texts } }
        } catch {
            await MainActor.run { withAnimation { storyError = true } }
        }
    }

    private func makeQuizChoices() -> [VocabItem] {
        let pool = VOCAB.filter { $0.id != vocab.id }.shuffled()
        return ([vocab] + pool.prefix(2)).shuffled()
    }

    var body: some View {
        ZStack {
            Color.cream.ignoresSafeArea()

            VStack(spacing: 0) {
                MissionHeader(title: "Story time", accent: .mint, onBack: { dismiss() })

                if storyTexts == nil && !storyError {
                    storyLoadingView
                    Spacer()
                } else {
                    switch phase {
                    case .reading(let page): readingView(page: page)
                    case .quiz:              quizView
                    }

                    Spacer()

                    ctaButton
                }
            }
        }
        .animation(.easeOut(duration: 0.3), value: phase)
        .task { await loadStory() }
    }

    /// Shown while Gemma writes the story.
    private var storyLoadingView: some View {
        VStack(spacing: 14) {
            Spacer()
            Mascot(state: .speaking, size: 88)
            Text("Q is writing today's story…")
                .font(.bodyText(15, weight: .bold))
                .foregroundStyle(Color.ink)
            ProgressView().tint(Color.mint)
            Spacer()
        }
        .frame(maxWidth: .infinity)
        .padding(.horizontal, 24)
    }

    // MARK: Reading
    private func readingView(page: Int) -> some View {
        let storyPage = pages[min(page, pages.count - 1)]
        return Group {
            if isLandscape {
                HStack(spacing: 0) {
                    storyCard(storyPage)
                        .frame(maxWidth: .infinity)
                    VStack(spacing: 12) {
                        progressBars(page: page)
                        narrationCard(storyPage)
                    }
                    .frame(maxWidth: .infinity)
                }
            } else {
                VStack(spacing: 12) {
                    progressBars(page: page)
                    storyCard(storyPage)
                    narrationCard(storyPage)
                }
            }
        }
    }

    private func progressBars(page: Int) -> some View {
        HStack(spacing: 6) {
            ForEach(0..<pages.count, id: \.self) { i in
                Capsule()
                    .fill(i <= page ? Color.mint : Color.inkFaint)
                    .frame(height: 4)
                    .animation(.easeOut(duration: 0.3), value: page)
            }
        }
        .padding(.horizontal, 24)
        .padding(.top, 8)
    }

    private func storyCard(_ storyPage: StoryPage) -> some View {
        ZStack {
            RoundedRectangle(cornerRadius: 22)
                .fill(storyPage.vocab.tone.bg)
                .grain()
                .popShadow()

            Sparkles(count: 4, opacity: 0.4)

            VStack(spacing: 16) {
                ObjectArt(vocab: storyPage.vocab, size: 100)
                Text(storyPage.vocab.hanzi)
                    .font(.display(36, weight: .heavy))
                    .foregroundStyle(storyPage.vocab.tone.fg)
            }
            .padding(24)
        }
        .frame(maxWidth: .infinity, minHeight: 200)
        .padding(.horizontal, 24)
    }

    private func narrationCard(_ storyPage: StoryPage) -> some View {
        ZStack {
            RoundedRectangle(cornerRadius: 16)
                .fill(Color.paper)
                .cardShadow()

            HStack(spacing: 12) {
                Mascot(state: .speaking, size: 48)
                Text(storyPage.text)
                    .font(.bodyText(14))
                    .foregroundStyle(Color.ink)
                    .fixedSize(horizontal: false, vertical: true)
                Spacer()
                Button {} label: {
                    QuackIcon(name: .speaker, size: 22, color: .quackOrange, strokeWidth: 2)
                }
                .buttonStyle(TapPress())
            }
            .padding(14)
        }
        .padding(.horizontal, 24)
    }

    // MARK: Quiz
    private var quizView: some View {
        Group {
            if isLandscape {
                HStack(spacing: 0) {
                    quizPrompt
                        .frame(maxWidth: .infinity)
                    quizChoices
                        .frame(maxWidth: .infinity)
                }
            } else {
                VStack(spacing: 16) {
                    quizPrompt
                    quizChoices
                }
            }
        }
        .onAppear {
            if quizChoicesCache == nil { quizChoicesCache = makeQuizChoices() }
        }
    }

    private var quizPrompt: some View {
        VStack(alignment: .leading, spacing: 4) {
            Eyebrow(text: "Quick quiz", flank: false, size: 11)
            Text("Which one is '\(vocab.hanzi)'?")
                .font(.display(22, weight: .heavy))
                .foregroundStyle(Color.ink)
        }
        .frame(maxWidth: .infinity, alignment: .leading)
        .padding(.horizontal, 24)
        .padding(.top, 8)
    }

    private var quizChoices: some View {
        let choices = quizChoicesCache ?? makeQuizChoices()
        return VStack(spacing: 10) {
            ForEach(choices) { choice in
                Button {
                    guard !quizRevealed else { return }
                    quizSelected = choice.id
                    withAnimation(.easeOut(duration: 0.3)) { quizRevealed = true }
                } label: {
                    HStack(spacing: 14) {
                        ObjectArt(vocab: choice, size: 52)
                        VStack(alignment: .leading, spacing: 2) {
                            Text(choice.en)
                                .font(.display(16, weight: .heavy))
                                .foregroundStyle(Color.ink)
                            Text(choice.pinyin)
                                .font(.bodyText(12))
                                .foregroundStyle(Color.inkMuted)
                        }
                        Spacer()
                        if quizRevealed && quizSelected == choice.id {
                            Circle()
                                .fill(choice.id == vocab.id ? Color.mintDeep : Color.quackOrange)
                                .frame(width: 26, height: 26)
                                .overlay(
                                    QuackIcon(
                                        name: choice.id == vocab.id ? .check : .close,
                                        size: 14, color: .white, strokeWidth: 2
                                    )
                                )
                        }
                    }
                    .padding(14)
                    .frame(maxWidth: .infinity)
                    .background(
                        RoundedRectangle(cornerRadius: 16)
                            .fill(quizRevealed && quizSelected == choice.id
                                  ? (choice.id == vocab.id ? Color.mint.opacity(0.3) : Color.rose.opacity(0.3))
                                  : Color.paper)
                    )
                    .cardShadow()
                }
                .buttonStyle(TapPress())
                .disabled(quizRevealed)
            }
        }
        .padding(.horizontal, 24)
    }

    // MARK: CTA
    @ViewBuilder
    private var ctaButton: some View {
        switch phase {
        case .reading(let page):
            CTAButton(
                label: page < pages.count - 1 ? "Next page" : "Take the quiz",
                variant: page < pages.count - 1 ? .ghost : .orange,
                action: {
                    if page < pages.count - 1 {
                        withAnimation { phase = .reading(page: page + 1) }
                    } else {
                        if quizChoicesCache == nil { quizChoicesCache = makeQuizChoices() }
                        withAnimation { phase = .quiz }
                    }
                }
            )
            .padding(.horizontal, 24)
            .padding(.bottom, 32)

        case .quiz:
            if quizRevealed {
                CTAButton(label: "Finish", variant: .ink, action: { onComplete(vocab.id) })
                    .padding(.horizontal, 24)
                    .padding(.bottom, 32)
                    .transition(.opacity.combined(with: .offset(y: 12)))
            }
        }
    }
}

#Preview {
    StoryMissionView(vocab: VOCAB[0], onComplete: { _ in })
        .environment(AppState())
}
